version: '3.9'

services:
  postgresqldb:
    image: postgres:14
    hostname: postgresqldb
    container_name: postgresqldb
    restart: unless-stopped
    networks:
      - mapper_voxter_rede
    environment:
      POSTGRES_DB: "conduktor-console"
      POSTGRES_USER: "conduktor"
      POSTGRES_PASSWORD: "change_me"
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"

  conduktor-console:
    image: conduktor/conduktor-console:1.23.0
    hostname: conduktor-console
    container_name: conduktor-console
    restart: unless-stopped
    networks:
      - mapper_voxter_rede
    depends_on:
      - postgresqldb
    ports:
      - "8098:8080"
    volumes:
      - type: bind
        source: "./platform-config.yml"
        target: /opt/conduktor/platform-config.yaml
        read_only: true
    environment:
      CDK_IN_CONF_FILE: /opt/conduktor/platform-config.yaml

  conduktor-monitoring:
    hostname: conduktor-monitoring
    container_name: conduktor-monitoring
    restart: unless-stopped
    image: conduktor/conduktor-console-cortex:1.23.0
    networks:
      - mapper_voxter_rede
    environment:
      CDK_CONSOLE-URL: "http://conduktor-console:8080"
      
networks:
  mapper_voxter_rede:
    external: true